project:  # Project information
    name: awesome-example-package
    description: >
        A pretty awesome package that will allow you to do
        awsome stuff, which is pretty awesome if you ask me.
    aern:

mammal:  # Mammal settings ----------------------------------------------------------
    kernels:
        default: aardvark
        required: { aardvark }

    writePrecompiledFiles: False

    dependencies:  # packages are loaded from packages.yml
        <<: !include dependencies.yml

    dependenciesLock:  # lock some versions which worked
        <<: !include dependencies.lock.yml

    style:
        indentation: 4 spaces  # options: "{n} spaces", "tabs", you cannot mix
        trailingCommas: all  # options: "all", "any", "none"
        numbers:
            scientific: "E"  # options: "any", "E", "10"
            padding: spaces  # options: "any", "none", "spaces", "zeros",
