#!/usr/bin/env mammal -v aardvark
""" Adds the used characters

    Many characters are used in mammal. But you are welcome
    to add more in your packages. All of utf8 is fair game.
"""


# Ascii characters

with __characters__ as c:
    c.setDefaultGroups(["latin", "lowercase"])
    c.add("a")
    c.add("b")
    c.add("c")
    c.add("d")
    c.add("e")
    c.add("f")
    c.add("g")
    c.add("h")
    c.add("i")
    c.add("j")
    c.add("k")
    c.add("l")
    c.add("m")
    c.add("n")
    c.add("o")
    c.add("p")
    c.add("q")
    c.add("r")
    c.add("s")
    c.add("t")
    c.add("u")
    c.add("v")
    c.add("w")
    c.add("x")
    c.add("y")
    c.add("z")

    c.setDefaultGroups(["latin", "uppercase"])
    c.add("A")
    c.add("B")
    c.add("C")
    c.add("D")
    c.add("E")
    c.add("F")
    c.add("G")
    c.add("H")
    c.add("I")
    c.add("J")
    c.add("K")
    c.add("L")
    c.add("M")
    c.add("N")
    c.add("O")
    c.add("P")
    c.add("Q")
    c.add("R")
    c.add("S")
    c.add("T")
    c.add("U")
    c.add("V")
    c.add("W")
    c.add("X")
    c.add("Y")
    c.add("Z")

    c.setDefaultGroups(["digit"])
    c.add("0", "zero")
    c.add("1", "one")
    c.add("2", "two")
    c.add("3", "three")
    c.add("4", "four")
    c.add("5", "five")
    c.add("6", "six")
    c.add("7", "seven")
    c.add("8", "eight")
    c.add("9", "nine")

    c.setDefaultGroups(["greek", "lowercase"])
    c.add("α", "alpha")
    c.add("β", "beta")
    c.add("γ", "gamma")
    c.add("δ", "delta")
    c.add("ε", "epsilon")
    c.add("ζ", "zeta")
    c.add("η", "eta")
    c.add("θ", "theta")
    c.add("ι", "iota")
    c.add("κ", "kappa")
    c.add("λ", "lambda")
    c.add("μ", "mu")
    c.add("ν", "nu")
    c.add("ξ", "xi")
    # c.add("ο", "omicron")  # not supported as it looks like o
    c.add("π", "pi")
    c.add("ρ", "rho")
    # c.add("ς", "sigma_final")  # not used in mathematics
    c.add("σ", "sigma")
    c.add("τ", "tau")
    c.add("υ", "upsilon")
    c.add("φ", "phi")
    c.add("χ", "chi")
    c.add("ψ", "psi")
    c.add("ω", "omega")

    c.add("ϐ", "beta_var")
    c.add("ϕ", "phi_var")
    c.add("ϑ", "theta_var")
    c.add("ϵ", "epsilon_var")

    c.setDefaultGroups(["greek", "uppercase"])
    c.add("Γ", "Gamma")
    c.add("Δ", "Delta")
    c.add("Θ", "Theta")
    c.add("Λ", "Lambda")
    c.add("Ξ", "Xi")
    c.add("Π", "Pi")
    c.add("Σ", "Sigma")
    c.add("Φ", "Phi")
    c.add("Ψ", "Psi")
    c.add("Ω", "Omega")

    c.setDefaultGroups(["latinExtended", "uppercase"])

    # German stuff
    # c.add("Ä", "A_uml")
    # c.add("Ö", "U_uml")
    # c.add("Ü", "U_uml")
    # c.add("ẞ", "SZ_lig")
    # c.add("Æ", "AE_lig")
    # c.add("Œ", "OE_lig")
    # c.add("Å", "A_circ")

    # c.setDefaultGroups(["latinExtended", "lowercase"])
    # c.add("ä", "a_uml")
    # c.add("ö", "o_uml")
    # c.add("ü", "u_uml")
    # c.add("ß", "sz_lig")
    # c.add("æ", "ae_lig")
    # c.add("œ", "oe_lig")

    c.setDefaultGroups(["operator"])
    c.add("+", "plus")
    c.add("−", "minus")
    c.add("-", "hyphen")
    c.add("⋅", "cdot")
    c.add(".", "dot")
    c.add("*", "asterisk")
    c.add("%", "percent")
    c.add("/", "slash")
    c.add("|", "pipe")
    c.add("&", "ampersand")
    c.add(r"\", "backslash", esc:=r"\")
    c.add("^", "caret")
    c.add("!", "exclamation", alt:=["exclamationMark"])
    c.add("?", "question", alt:=["questionMark"])
    c.add("@", "at")
    c.add("~", "tilde")
    c.add("∘", "circ")
    c.add("∇", "nabla")

    c.setDefaultGroups(["operator", "set"])
    c.add("∪", "union")
    c.add("∩", "intersect")

    c.setDefaultGroups(["operator", "comparison"])
    c.add("<", "lower")
    c.add("≤", "lowerEqual")
    c.add(">", "greater")
    c.add("≥", "greaterEqual")
    c.add("=", "equals", alt:=["equal"])
    c.add("≠", "notEqual")
    c.add("≈", "aprox")
    c.add("≡", "equiv")

    c.setDefaultGroups(["operator", "comparison", "set"])
    c.add("⊂", "subset")
    c.add("⊆", "subsetEqual")
    c.add("⊃", "superset")
    c.add("⊇", "supersetEqual")


    c.setDefaultGroups(["mathematics"])
    c.add("­∅", "emptySet")
    c.add("∞", "infinity", alt:=["lemniscate"])
    # c.add("⊥", "perpendicular")
    c.add("ℓ", "l_calig")
    # c.add("ℵ", "aleph")
    # c.add("∫", "integral")
    # c.add("√", "root")
    c.add("ℂ", "complexNumbers")
    c.add("ℕ", "naturalNumbers")
    c.add("ℚ", "rationalNumbers")
    c.add("ℝ", "realNumbers")
    c.add("ℤ", "integers")

    c.setDefaultGroups(["quotationMark"])
    c.add("'", "singleQuote")
    c.add('"', "doubleQuote")
    c.add('`', "backtick")
    # c.add("‹", "singleGuillemetOpen")
    # c.add("›", "singleGuillemetClose")
    # c.add("«", "doubleGuillemetOpen")
    # c.add("»", "doubleGuillemetClose")

    c.setDefaultGroups(["bracket", "opening"])
    c.add("(", "bracketOpen")
    c.add("[", "squareBracketOpen")
    c.add("{", "curlyBracketOpen")

    c.setDefaultGroups(["bracket", "closing"])
    c.add(")", "bracketClose")
    c.add("]", "squareBracketClose")
    c.add("}", "curlyBracketClose")

    c.setDefaultGroups(["separator"])
    c.add(" ", "space")
    c.add("\t", "tabulator", esc:="t")
    c.add("\n", "newline", esc:="n")
    c.add("…", "ellipsis")
    c.add(",", "comma")
    c.add(";", "semicolon")
    c.add(":", "colon")

    # c.setDefaultGroups(["currency"])
    # c.add("$", "dollar")
    # c.add("€", "euro")  # probably will be obsolete shortly
    # c.add("¥", "yen")
    # c.add("¢", "cent")
    # c.add("£", "pound")

    c.setDefaultGroups(["miscellaneous"])
    c.add("_", "underscore")
    c.add("#", "hash")
    # c.add("§", "paragraph")

    c.setDefaultGroups(["digits", "raised"])
    c.add("⁰", "zero_raised")
    c.add("¹", "one_raised")
    c.add("²", "two_raised")
    c.add("³", "three_raised")
    c.add("⁴", "four_raised")
    c.add("⁵", "five_raised")
    c.add("⁶", "six_raised")
    c.add("⁷", "seven_raised")
    c.add("⁸", "eight_raised")
    c.add("⁹", "nine_raised")

    c.setDefaultGroups(["operator", "raised"])
    c.add("⁺", "plus_raised")
    c.add("⁻", "minus_raised")
